# Site settings
title: Michael Lavelle
description: 'Business Card Page'
url: 'https://michaellavelle.github.io'
baseurl: ''
profilepic: '/images/michaellavelle.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Michael Lavelle'
  email: michael@lavelle.name
  twitter_username: michaellavelle
#  facebook_username: joshgerdes
  github_username: michaellavelle 
  linkedin_username: michaellavelle 

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
